### ISSUE TITLE
테스트 통계 owner 제외

### ISSUE THREAD

**Issue by street62** [Nexters/keyme-backend#158]
### Description
현재 각 테스트별 통계 조회 요청 시 owner의 TestResult가 포함되어 solverCount, 평균 matchRate가 의도한 대로 동작하지 않습니다. owner의 result는 제외하도록 수정이 필요합니다.

**Comment by RokwonK** [comment]
와 Question에서는 뺏는데 Test에서 빼지 않았군요 감사합니다.
